### ISSUE TITLE
Support problem

### ISSUE THREAD

**Issue by omarargueles** [brownieboy/react.bootstrap.slidertest#1]
You are doing a wrapper that show two options

1 = react-html5-slider: When you have native support or a polyfill
2 = react-bootstrap-slider: When you have not native support or polyfill

Promblem: react-bootstrap-slider is just a wrapper over "seiyria/bootstrap-slider", but in the documentation of this project they are adding:
"We only support modern browsers!!! Basically, anything below IE9 is not compatible with this plugin!", and react-bootstrap-slider is not adding any polyfill.

Conclusion: Why are you using react-bootstrap-slider as the fallback component if seiyria/bootstrap-slider doesn't give support for anything below IE9?, I recommend to add a polyfill to react-bootstrap-slider and by this way it will be working nice.

**Comment by brownieboy** [comment]
For a start, you've posted this report in an obsolete repository, which you would have seen if you'd read the readme.

Thank you for your suggestion, but I have no intention of spending any of my time supporting older versions of IE.  FYI, Microsoft made all browsers lower than IE 11 End of Life in January 2016 - [read all about it](https://www.microsoft.com/en-au/WindowsForBusiness/End-of-IE-support).

If you have users on IE 8 or lower - presumably they're running Windows XP (also End of Life) too? -  then that's your problem, and you're welcome to try and fix it.  You can fork my code as a start.  That's the beauty of Open Source!

Best of luck.
