### ISSUE TITLE
Use webpack or browserify to allow component to be used with react apps that use webpack or browserfy

### ISSUE THREAD

**Issue by jewelsjacobs** [brownieboy/react.bootstrap.slidertest#2]
See https://github.com/nnarhinen/react-bootstrap-async-autocomplete as an example of using browserify to make sure dependacies are included in the compiled version of the component.

**Comment by jewelsjacobs** [comment]
Thanks so much!

Can you pls re-publish the module to the npm repo so I can install the version (react-bootstrap-native-slider@1.0.3) with this change?  Thanks!

**Comment by brownieboy** [comment]
Module just republished to npm, as requested.

**Comment by jewelsjacobs** [comment]
Awesome!  Thanks so much!  And thanks for the cool mod!
